# -*- coding: utf-8 -*-
"""Prathamesh Murkute Task 2 PREDICTIVE ANALYSIS USING MACHINE LEARNING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmxMTQw_hy1oaRFgURtFJGOkmSe8n3xg
"""

pip install pandas matplotlib seaborn scikit-learn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("/content/drive/MyDrive/task data set/College.csv")

# View first few rows
print(df.head())

# Check for nulls
print(df.isnull().sum())

# Overview
print(df.describe())

le = LabelEncoder()
df['Private'] = le.fit_transform(df['Private'])

df = df.drop(columns=['Unnamed: 0'], errors='ignore')

X = df.drop('Outstate', axis=1)
y = df['Outstate']

plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.show()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.2f}")
print(f"R-squared: {r2:.2f}")

plt.scatter(y_test, y_pred, alpha=0.7)
plt.xlabel("Actual Outstate Fees")
plt.ylabel("Predicted Outstate Fees")
plt.title("Actual vs Predicted Outstate Tuition")
plt.show()